# Generated by Django 3.2.3 on 2021-05-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploads',
            new_name='Upload',
        ),
    ]
