# Generated by Django 3.2.3 on 2021-05-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_rename_uploads_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
