# Generated by Django 3.2.3 on 2021-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_alter_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
