# Generated by Django 3.2.3 on 2021-05-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_alter_upload_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='sca',
            field=models.CharField(choices=[('YES', 'yes')], default='YES', max_length=50),
        ),
    ]
