# Generated by Django 3.2.3 on 2021-05-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_upload_sca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='sca',
            field=models.CharField(choices=[('YES', 'yes')], default='NO', max_length=50),
        ),
    ]
